### Rappi_Campus - Prueba de Endpoinst
### REPARTIDORES ---------------------------------------------------------------------------------------------
### Register Repartidor
POST http://localhost:3000/auth/repartidores/register 
Content-Type: application/json  

{
    "nombre": "Luis",
    "contrasena": "123456a",
    "apellido": "Gomeza",
    "correo": "luis_gomeza@gmail.com",
    "numero_celular": "3001234567a",
    "cedula": "33333a",
    "fecha_nacimiento": "1990-01-01",
    "sexo": "M",
    "tipo_vehiculo": "Carro"
}

### Login Repartidor
POST http://localhost:3000/auth/repartidores/login
Content-Type: application/json
//Accept-Version: 1.0.0

{
    "correo": "luis_gomeza@gmail.com",
    "contrasena": "123456a"
}

### Obtiene todos los repartidores
GET http://localhost:3000/v1/repartidores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZjYyZTc4MmE1ZGRjMTc4Y2RhYWViOCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5Mzg1NTM5NSwiZXhwIjoxNjkzODU4OTk1fQ.Fmtqbx7poi7sVOUGLB7vGC7rMtlTeGMA3xhpTnr1A_k


### Obtener repartidor por id
GET http://localhost:3000/v1/repartidores/2
Headers: Accept-Version: 1.0.0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZjYyZTc4MmE1ZGRjMTc4Y2RhYWViOCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5Mzg1NTM5NSwiZXhwIjoxNjkzODU4OTk1fQ.Fmtqbx7poi7sVOUGLB7vGC7rMtlTeGMA3xhpTnr1A_k

### Obtener repartidor por cedula
GET http://localhost:3000/v1/repartidores/cedula/123456781
Headers: Accept-Version: 1.0.0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

### Obtener repartidor por correo
GET http://localhost:3000/v1/repartidores/correo/luisgomez@gmail.com
Headers: Accept-Version: 1.0.0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

### Actualizar repartidor --- QUE SOLO EL USUARIO DEL TOKEN PUEDA ACTUALIZAR SU INFORMACION
PUT http://localhost:3000/v1/repartidores/4
Headers: Accept-Version: 1.0.0
Content-Type: application/json

{
    "apellido": "Fernando",
    "correo": "luis_fernando@gmail.com"
}

### Eliminar repartidor --- QUE SOLO EL USUARIO DEL TOKEN PUEDA ELIMINAR SU INFORMACION
DELETE http://localhost:3000/v1/repartidores/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZjYyZTc4MmE1ZGRjMTc4Y2RhYWViOCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5Mzg1NTM5NSwiZXhwIjoxNjkzODU4OTk1fQ.Fmtqbx7poi7sVOUGLB7vGC7rMtlTeGMA3xhpTnr1A_k

### PEDIDOS         ---------------------------------------------------------------------------------------------

### Obtiene todos los pedidos - con token de Repartidor
GET http://localhost:3000/pedidos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

### Obtener pedido por id
GET http://localhost:3000/pedidos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

### Obtener pedidos por id de cliente
GET http://localhost:3000/pedidos/cliente/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

### Obtener pedidos por id de repartidor
GET http://localhost:3000/pedidos/repartidor/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

### Obtener pedidos por id de restaurante
GET http://localhost:3000/pedidos/restaurante/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

### Crear pedido - SOLO CON TOKEN DE CLIENTE
POST http://localhost:3000/pedidos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

Content-Type: application/json

{
    "id_cliente": 99,
    "id_repartidor": 99,
    "id_restaurante": 99,
    "productos": [
        {
            "id_producto": 1,
            "cantidad": 2
        },
        {
            "id_producto": 2,
            "cantidad": 1
        }
    ],
    "metodo_pago": "Efectivo",
    "valor_total": 20000,
    "fecha_pedido": "2023-08-25"
}

### Actualizar pedido -- SOLO CON TOKEN DE CLIENTE
PUT http://localhost:3000/pedidos/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

Content-Type: application/json

{
    "id_cliente": 12,
    "id_repartidor": 44
}

### Eliminar pedido
DELETE http://localhost:3000/pedidos/19 -- SOLO CON TOKEN DE CLIENTES
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;


### RESTAURANTES                ---------------------------------------------------------------------------------------------

### Obtiene todos los restaurantes
GET http://localhost:3000/restaurantes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;
### Obtener restaurante por id
GET http://localhost:3000/restaurantes/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

### Crear restaurante -- SOLO CON TOKEN DE RESTAURANTE
POST http://localhost:3000/restaurantes 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

Content-Type: application/json

{
    "nombre": "Restaurxante 3",
    "direccion": "Calle 3 # 2-2",
    "numero_celular": "33455",
    "correo": "restauran44te3@gmail.com",
    "horario_atencion": "Lunes a Viernes 8:00 am - 5:00 pm",
    "foto_restaurante": "https://www.eltiempo.com/files/image_640_428/uploads/2019/08/22/5d5e9b3a1e0e7.jpeg"
}

### Actualizar restaurante
PUT http://localhost:3000/restaurantes/11 -- SOLO CON TOKEN DE RESTAURANTE
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

Content-Type: application/json

{
    "nombre": "Restaurxante 44444"
}

### Eliminar restaurante
DELETE http://localhost:3000/restaurantes/11 -- SOLO CON TOKEN DE RESTAURANTE
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;



### CLIENTES ---------------------------------------------------------------------------------------------

### Register Cliente
POST http://localhost:3000/auth/clientes/register 
Content-Type: application/json

{
    "nombre": "Gerson",
    "apellido": "Hernández",
    "correo": "gersonhdz@gmail.com",
    "direccion_entrega": "Calle 26a # 11-30",
    "numero_celular": "3122341234",
    "cedula": "1096243865",
    "fecha_nacimiento": "1998-10-20",
    "sexo": "M",
    "contrasena": "123456"
}

### Login Cliente
POST http://localhost:3000/auth/clientes/login
Content-Type: application/json

{
    "correo": "gersonhdz@gmail.com",
    "contrasena": "123456"
}

### Obtiene todos los clientes
GET http://localhost:3000/clientes/getAllClient
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVkZGExZTNhZjFjZjhkNmVmZDcxYyIsInJvbCI6ImNsaWVudGVzIiwiaWF0IjoxNjkzMzc1OTg1LCJleHAiOjE2OTMzNzk1ODV9.ClfTwdLHY9uoAmwljSVWoYSgU-q_eYTPq3Ll-5WqcZ8;

### Obtener clientes por id

GET http://localhost:3000/clientes/getClient/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

### Actualizar Cliente

PUT http://localhost:3000/clientes/update/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

Content-Type: application/json

{
    "apellido": "Olave",
    "correo": "gersonhdz4@gmail.com"
}

### Eliminar Cliente

DELETE http://localhost:3000/clientes/delete/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;



### PRODUCTOS ---------------------------------------------------------------------------------------------

### Obtiene todos los productos
GET http://localhost:3000/productos/getAllProduct
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;


### Obtener productos por id
GET http://localhost:3000/productos/getProduct/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;


### Obtener productos por id de restaurante
GET http://localhost:3000/productos/getProductByRestaurant/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;


### Crear producto
POST http://localhost:3000/productos/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

Content-Type: application/json

{
    "id_restaurante": 2,
    "nombre": "Lasagna",
    "valor_unitario": 20000,
    "descripcion": "Lasagna mixta",
    "foto_producto": "https://images.pexels.com/photos/5864352/pexels-photo-5864352.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "stock": 20
}
### Actualizar Producto por id
PUT http://localhost:3000/productos/update/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;

Content-Type: application/json

{
    "nombre": "Huevo Frito",
    "valor_unitario": 10000,
    "descripcion": "Huevo frito sin sal",
    "foto_producto": "https://images.pexels.com/photos/7937471/pexels-photo-7937471.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "stock": 50
}

### Eliminar Producto por id 
DELETE http://localhost:3000/productos/delete/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;


### Eliminar todos los productos de un restaurent por id de restaurante
DELETE http://localhost:3000/productos/deleteByRestaurant/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWVlMzA3M2ZiNzM4MjAyOTk1YTZmMCIsInJvbCI6InJlcGFydGlkb3JlcyIsImlhdCI6MTY5MzM3NzMzMCwiZXhwIjoxNjkzMzgwOTMwfQ.P3Tty_b7cYx0cOPNmAVyaMTb5od0TZg1d2agnwOhFfI;
