### Rappi_Campus - Prueba de Endpoinst
### REPARTIDORES ---------------------------------------------------------------------------------------------

### Obtiene todos los repartidores
GET http://localhost:3000/repartidores
### Obtener repartidor por id
GET http://localhost:3000/repartidores/1
### Obtener repartidor por cedula
GET http://localhost:3000/repartidores/cedula/123456781
### Obtener repartidor por correo
GET http://localhost:3000/repartidores/correo/luisgomez@gmail.com
### Crear repartidor
POST http://localhost:3000/repartidores
Content-Type: application/json

{

    "nombre": "Luis",
    "apellido": "Gomez",
    "correo": "luis_gomez@gmail.com",
    "numero_celular": "3001234567",
    "cedula": "33333",
    "fecha_nacimiento": "1990-01-01",
    "sexo": "M",
    "tipo_vehiculo": "Carro"
}
### Actualizar repartidor
PUT http://localhost:3000/repartidores/4
Content-Type: application/json

{
    "apellido": "Fernando",
    "correo": "luis_fernando@gmail.com"
}

### Eliminar repartidor
DELETE http://localhost:3000/repartidores/4

### PEDIDOS         ---------------------------------------------------------------------------------------------

### Obtiene todos los pedidos
GET http://localhost:3000/pedidos
### Obtener pedido por id
GET http://localhost:3000/pedidos/2
### Obtener pedidos por id de cliente
GET http://localhost:3000/pedidos/cliente/1
### Obtener pedidos por id de repartidor
GET http://localhost:3000/pedidos/repartidor/1
### Obtener pedidos por id de restaurante
GET http://localhost:3000/pedidos/restaurante/1
### Crear pedido
POST http://localhost:3000/pedidos
Content-Type: application/json

{
    "id_cliente": 99,
    "id_repartidor": 99,
    "id_restaurante": 99,
    "productos": [
        {
            "id_producto": 1,
            "cantidad": 2
        },
        {
            "id_producto": 2,
            "cantidad": 1
        }
    ],
    "metodo_pago": "Efectivo",
    "valor_total": 20000,
    "fecha_pedido": "2023-08-25"
}

### Actualizar pedido
PUT http://localhost:3000/pedidos/19
Content-Type: application/json

{
    "id_cliente": 12,
    "id_repartidor": 44
}

### Eliminar pedido
DELETE http://localhost:3000/pedidos/19

### RESTAURANTES                ---------------------------------------------------------------------------------------------

### Obtiene todos los restaurantes
GET http://localhost:3000/restaurantes
### Obtener restaurante por id
GET http://localhost:3000/restaurantes/11
### Crear restaurante
POST http://localhost:3000/restaurantes
Content-Type: application/json

{
    "nombre": "Restaurxante 3",
    "direccion": "Calle 3 # 2-2",
    "numero_celular": "33455",
    "correo": "restauran44te3@gmail.com",
    "horario_atencion": "Lunes a Viernes 8:00 am - 5:00 pm",
    "foto_restaurante": "https://www.eltiempo.com/files/image_640_428/uploads/2019/08/22/5d5e9b3a1e0e7.jpeg"
}

### Actualizar restaurante
PUT http://localhost:3000/restaurantes/11
Content-Type: application/json

{
    "nombre": "Restaurxante 44444"
}

### Eliminar restaurante
DELETE http://localhost:3000/restaurantes/11


### CLIENTES ---------------------------------------------------------------------------------------------

### Obtiene todos los clientes
GET http://localhost:3000/clientes/getAllClient

### Obtener clientes por id
GET http://localhost:3000/clientes/getClient/2

### Crear cliente
POST http://localhost:3000/clientes/create
Content-Type: application/json

{

    "nombre": "Gerson",
    "apellido": "Hernández",
    "correo": "gersonhdz@gmail.com",
    "direccion_entrega": "Calle 26a # 11-30",
    "numero_celular": "3122341234",
    "cedula": "1096243865",
    "fecha_nacimiento": "1998-10-20",
    "sexo": "M"
}
### Actualizar Cliente
PUT http://localhost:3000/clientes/update/2
Content-Type: application/json

{
    "apellido": "Olave",
    "correo": "gersonhddddd@gmail.com"
}

### Eliminar Cliente
DELETE http://localhost:3000/clientes/delete/2